// Layout der ganzen Homepage

import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';
import HangukSessionProvider from '@/providers/hanguk-session-provider';

const raleway = Raleway({ 
  subsets: ['latin'], 
}); // noch dazu??????

export const metadata: Metadata = {
  title: 'HangukJingu', // Create Next App
description: 'Generated by create next app', // muss das sein
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <HangukSessionProvider>
          <Header />
            {children}
          <Footer />
        </HangukSessionProvider>
      </body>
    </html>
  );
}
